# custom_postgres/models/example/schema.yml

version: 2

models:
  - name: users
    description: "Table containing user information"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "User's first name"
      - name: last_name
        description: "User's last name"
      - name: email
        description: "User's email address"
        tests:
          - unique
          - not_null
      - name: date_of_birth
        description: "User's date of birth"
    meta:
      owner: "data_team"
    tags: ["user_data", "important"]

  - name: films
    description: "Table containing film information"
    columns:
      - name: film_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film"
        tests:
          - unique
          - not_null
      - name: release_date
        description: "Release date of the film"
        tests:
          - not_null
      - name: price
        description: "Price of the film"
        tests:
          - not_null
      - name: rating
        description: "Film rating"
        tests:
          - not_null
      - name: user_rating
        description: "User rating of the film"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
    tags: ["film_data"]

  - name: film_category
    description: "Table linking films to their categories"
    columns:
      - name: category_id
        description: "id for categories"
        tests:
          - not_null
      - name: film_id
        description: "Foreign key referencing films"
        tests:
          - not_null
      - name: category_name
        description: "Name of the category"
        tests:
          - not_null
    tags: ["category_data"]

  - name: actors
    description: "Table containing actor information"
    columns:
      - name: actor_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: actor_name
        description: "Name of the actor"
        tests:
          - not_null
    tags: ["actor_data"]

  - name: film_actors
    description: "Table linking films to their actors"
    columns:
      - name: film_id
        description: "Foreign key referencing films"
      - name: actor_id
        description: "Foreign key referencing actors"
    tags: ["film_actor_data"]